# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='egg_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='egg_reward',
            field=models.IntegerField(default=0),
        ),
    ]
