# Generated by Django 6.0.2 on 2026-02-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_add_egg_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary')], default='Common', max_length=20),
        ),
    ]
