# Generated by Django 6.0.2 on 2026-02-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemon_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonunlock',
            name='shiny',
            field=models.BooleanField(default=False),
        ),
    ]
