# Generated by Django 6.0.2 on 2026-02-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_pokemonunlock_shiny'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokeapi_id',
            field=models.IntegerField(default=0),
        ),
    ]
