# Generated by Django 6.0.2 on 2026-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_trainer_pokeball_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='shiny_luck',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='max_team_size',
            field=models.IntegerField(default=6),
        ),
    ]
