# Generated by Django 6.0.2 on 2026-02-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_trainer_shiny_luck_alter_trainer_max_team_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('item_type', models.CharField(choices=[('egg', 'Egg'), ('pokeball', 'Pokeball'), ('boost', 'Boost'), ('cosmetic', 'Cosmetic')], max_length=20)),
                ('icon', models.CharField(default='🎁', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='trainer',
            name='hunt_coins',
            field=models.IntegerField(default=100),
        ),
    ]
