# Generated by Django 6.0.2 on 2026-02-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_shopitem_trainer_hunt_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
