# Generated by Django 6.0.2 on 2026-02-24 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_shopitem_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('egg', 'Eggs'), ('pokeball', 'Pokeballs'), ('berry', 'Berries'), ('potion', 'Potions'), ('status_heal', 'Status Heals'), ('evolution', 'Evolution Items'), ('vitamin', 'Vitamins'), ('exp', 'EXP Candies'), ('cosmetic', 'Cosmetics')], default='pokeball', max_length=20)),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.shopitem')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pokemon.trainer')),
            ],
            options={
                'unique_together': {('trainer', 'shop_item')},
            },
        ),
    ]
