# Generated by Django 6.0.2 on 2026-02-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='coin_reward',
            field=models.IntegerField(default=0),
        ),
    ]
