from django.core.management.base import BaseCommand
from pokemon.models import Pokemon, DailyTask


class Command(BaseCommand):
    help = 'Populate database with real Pokemon and daily tasks using PokeAPI sprites'

    def handle(self, *args, **options):
        # Clear existing data
        Pokemon.objects.all().delete()
        DailyTask.objects.all().delete()
        
        # Create 150+ real Pokemon across all generations with PokeAPI sprites
        pokemon_data = [
            # Gen 1 Starters
            {'name': 'Bulbasaur', 'type': 'Grass', 'level_requirement': 1, 'is_starter': True,
             'description': 'A strange seed was planted on its back at birth. The bulb sprouts and grows with this Pokemon.',
             'pokeapi_id': 1, 'rarity': 'Common'},
            {'name': 'Charmander', 'type': 'Fire', 'level_requirement': 1, 'is_starter': True,
             'description': 'The flame that burns at the tip of its tail is an indication of its emotions.',
             'pokeapi_id': 4, 'rarity': 'Common'},
            {'name': 'Squirtle', 'type': 'Water', 'level_requirement': 1, 'is_starter': True,
             'description': 'When it retracts its long neck into its shell, it squirts out water with vigorous force.',
             'pokeapi_id': 7, 'rarity': 'Common'},
            
            # Gen 1 - Early
            {'name': 'Pikachu', 'type': 'Electric', 'level_requirement': 2, 'is_starter': False,
             'description': 'It stores electricity in the electric pouches on its cheeks.',
             'pokeapi_id': 25, 'rarity': 'Uncommon'},
            {'name': 'Jigglypuff', 'type': 'Normal', 'level_requirement': 2, 'is_starter': False,
             'description': 'When it wavers its delicate, freshly inflated cheeks, it sings a lullaby.',
             'pokeapi_id': 39, 'rarity': 'Uncommon'},
            {'name': 'Psyduck', 'type': 'Water', 'level_requirement': 3, 'is_starter': False,
             'description': 'It is constantly beset by headaches. If they get worse, it starts using mysterious psychic powers.',
             'pokeapi_id': 54, 'rarity': 'Common'},
            {'name': 'Gastly', 'type': 'Ghost', 'level_requirement': 3, 'is_starter': False,
             'description': 'It wraps its opponent in its gas-like body, weakening its prey by poisoning it.',
             'pokeapi_id': 92, 'rarity': 'Rare'},
            {'name': 'Machop', 'type': 'Fighting', 'level_requirement': 3, 'is_starter': False,
             'description': 'Its whole body is composed of muscles. Even when still, it appears to be always moving.',
             'pokeapi_id': 66, 'rarity': 'Common'},
            {'name': 'Geodude', 'type': 'Rock', 'level_requirement': 3, 'is_starter': False,
             'description': 'It is commonly found near mountains and hills. It rolls toward anything that comes near.',
             'pokeapi_id': 74, 'rarity': 'Common'},
            {'name': 'Poliwag', 'type': 'Water', 'level_requirement': 4, 'is_starter': False,
             'description': 'It is weak to attacks from outside. It spins its legs to swim in the water.',
             'pokeapi_id': 60, 'rarity': 'Common'},
            {'name': 'Abra', 'type': 'Psychic', 'level_requirement': 4, 'is_starter': False,
             'description': 'It sleeps for 18 hours a day. It can teleport away when threatened.',
             'pokeapi_id': 63, 'rarity': 'Rare'},
            {'name': 'Oddish', 'type': 'Grass', 'level_requirement': 4, 'is_starter': False,
             'description': 'It often plants its feet deep underground. It searches for fertilizer.',
             'pokeapi_id': 43, 'rarity': 'Common'},
            {'name': 'Caterpie', 'type': 'Bug', 'level_requirement': 2, 'is_starter': False,
             'description': 'It has a voracious appetite. It can devour leaves bigger than its body in one bite.',
             'pokeapi_id': 10, 'rarity': 'Common'},
            {'name': 'Weedle', 'type': 'Bug', 'level_requirement': 2, 'is_starter': False,
             'description': 'It has a potent venomous stinger on its head. Beware of its sharp bite.',
             'pokeapi_id': 13, 'rarity': 'Common'},
            {'name': 'Rattata', 'type': 'Normal', 'level_requirement': 2, 'is_starter': False,
             'description': 'It is cautious and quick to flee. It lives in colonies.',
             'pokeapi_id': 19, 'rarity': 'Common'},
            {'name': 'Ekans', 'type': 'Poison', 'level_requirement': 3, 'is_starter': False,
             'description': 'It moves silently and stealthily. It coils around prey and injects venom.',
             'pokeapi_id': 23, 'rarity': 'Common'},
            {'name': 'Sandshrew', 'type': 'Ground', 'level_requirement': 3, 'is_starter': False,
             'description': 'It burrows deep underground. It can roll into a ball to defend itself.',
             'pokeapi_id': 27, 'rarity': 'Common'},
            
            # Gen 1 - Mid
            {'name': 'Growlithe', 'type': 'Fire', 'level_requirement': 5, 'is_starter': False,
             'description': 'It is fiercely brave and loyal. It fearlessly stands up to bigger enemies.',
             'pokeapi_id': 58, 'rarity': 'Rare'},
            {'name': 'Poliwhirl', 'type': 'Water', 'level_requirement': 5, 'is_starter': False,
             'description': 'Its legs are well developed. It can get around on land despite being a Water-type.',
             'pokeapi_id': 61, 'rarity': 'Uncommon'},
            {'name': 'Kadabra', 'type': 'Psychic', 'level_requirement': 6, 'is_starter': False,
             'description': 'It emits a peculiar alpha wave from its body that induces headaches.',
             'pokeapi_id': 64, 'rarity': 'Rare'},
            {'name': 'Slowpoke', 'type': 'Water', 'level_requirement': 6, 'is_starter': False,
             'description': 'It is not very bright. It takes a long time to respond to stimuli.',
             'pokeapi_id': 79, 'rarity': 'Common'},
            {'name': 'Magnemite', 'type': 'Electric', 'level_requirement': 6, 'is_starter': False,
             'description': 'It is surrounded by electricity. It interferes with electronic devices.',
             'pokeapi_id': 81, 'rarity': 'Uncommon'},
            {'name': 'Drowzee', 'type': 'Psychic', 'level_requirement': 6, 'is_starter': False,
             'description': 'It puts its prey to sleep and then feeds on their dreams. Yawn!',
             'pokeapi_id': 96, 'rarity': 'Common'},
            {'name': 'Krabby', 'type': 'Water', 'level_requirement': 5, 'is_starter': False,
             'description': 'It lives in burrows dug into sandy beaches. Its pincers are very strong.',
             'pokeapi_id': 98, 'rarity': 'Common'},
            {'name': 'Voltorb', 'type': 'Electric', 'level_requirement': 5, 'is_starter': False,
             'description': 'It is said to have been created when a Pokeball was exposed to mysterious energy.',
             'pokeapi_id': 100, 'rarity': 'Common'},
            {'name': 'Exeggcute', 'type': 'Grass', 'level_requirement': 5, 'is_starter': False,
             'description': 'It consists of six eggs that form a cluster. They are each very delicate.',
             'pokeapi_id': 102, 'rarity': 'Uncommon'},
            {'name': 'Cubone', 'type': 'Ground', 'level_requirement': 5, 'is_starter': False,
             'description': 'It wears the skull of its deceased mother. It is very sad.',
             'pokeapi_id': 104, 'rarity': 'Rare'},
            {'name': 'Hitmonlee', 'type': 'Fighting', 'level_requirement': 8, 'is_starter': False,
             'description': 'It has lightning-fast kicks. It can kick even faster than it can punch.',
             'pokeapi_id': 106, 'rarity': 'Epic'},
            {'name': 'Hitmonchan', 'type': 'Fighting', 'level_requirement': 8, 'is_starter': False,
             'description': 'It can punch at incredible speed. Its punches are as fast as bullets.',
             'pokeapi_id': 107, 'rarity': 'Epic'},
            {'name': 'Lickitung', 'type': 'Normal', 'level_requirement': 7, 'is_starter': False,
             'description': 'Its tongue is incredibly long. It can lick anything within reach.',
             'pokeapi_id': 108, 'rarity': 'Rare'},
            {'name': 'Koffing', 'type': 'Poison', 'level_requirement': 6, 'is_starter': False,
             'description': 'It mixes its gases with the surrounding air. Very toxic.',
             'pokeapi_id': 109, 'rarity': 'Common'},
            
            # Gen 1 - Evolutions
            {'name': 'Ponyta', 'type': 'Fire', 'level_requirement': 7, 'is_starter': False,
             'description': 'Its hooves are 10 times harder than diamonds. It can trod on any surface.',
             'pokeapi_id': 77, 'rarity': 'Uncommon'},
            {'name': 'Rapidash', 'type': 'Fire', 'level_requirement': 12, 'is_starter': False,
             'description': 'It can run at speeds of 150 mph. Its mane glows when it runs.',
             'pokeapi_id': 78, 'rarity': 'Rare'},
            {'name': 'Slowbro', 'type': 'Water', 'level_requirement': 12, 'is_starter': False,
             'description': 'A Shellder bit its tail. Now it cant live without water.',
             'pokeapi_id': 80, 'rarity': 'Rare'},
            {'name': 'Magneton', 'type': 'Electric', 'level_requirement': 10, 'is_starter': False,
             'description': 'Three Magnemite are linked by a magnetic force. Very dangerous.',
             'pokeapi_id': 82, 'rarity': 'Rare'},
            {'name': 'Farfetchd', 'type': 'Normal', 'level_requirement': 8, 'is_starter': False,
             'description': 'It always carries a stick. It uses the stick to fight and for defense.',
             'pokeapi_id': 83, 'rarity': 'Rare'},
            {'name': 'Doduo', 'type': 'Normal', 'level_requirement': 7, 'is_starter': False,
             'description': 'Its two heads coordinate perfectly. It can run faster than a racehorse.',
             'pokeapi_id': 84, 'rarity': 'Uncommon'},
            {'name': 'Seel', 'type': 'Water', 'level_requirement': 7, 'is_starter': False,
             'description': 'It loves cold climates. It can survive temperatures as low as -40 degrees.',
             'pokeapi_id': 86, 'rarity': 'Uncommon'},
            {'name': 'Grimer', 'type': 'Poison', 'level_requirement': 7, 'is_starter': False,
             'description': 'It is made of sludge. It leaves a trail of sludge wherever it goes.',
             'pokeapi_id': 88, 'rarity': 'Common'},
            {'name': 'Shellder', 'type': 'Water', 'level_requirement': 7, 'is_starter': False,
             'description': 'Its hard shell is impervious to most attacks. Very durable.',
             'pokeapi_id': 90, 'rarity': 'Uncommon'},
            {'name': 'Gengar', 'type': 'Ghost', 'level_requirement': 12, 'is_starter': False,
             'description': 'It can hide in shadows. It steals life force from sleeping prey.',
             'pokeapi_id': 94, 'rarity': 'Epic'},
            {'name': 'Onix', 'type': 'Rock', 'level_requirement': 8, 'is_starter': False,
             'description': 'It burrows through the ground at 50 mph. Very dangerous.',
             'pokeapi_id': 95, 'rarity': 'Rare'},
            {'name': 'Hypno', 'type': 'Psychic', 'level_requirement': 12, 'is_starter': False,
             'description': 'It puts people to sleep and feeds on their dreams. Very dangerous.',
             'pokeapi_id': 97, 'rarity': 'Rare'},
            {'name': 'Kingler', 'type': 'Water', 'level_requirement': 10, 'is_starter': False,
             'description': 'Its huge pincers can crush anything. Very powerful.',
             'pokeapi_id': 99, 'rarity': 'Rare'},
            {'name': 'Electrode', 'type': 'Electric', 'level_requirement': 10, 'is_starter': False,
             'description': 'It stores electricity at high voltage. It can explode at any moment.',
             'pokeapi_id': 101, 'rarity': 'Rare'},
            {'name': 'Exeggutor', 'type': 'Grass', 'level_requirement': 12, 'is_starter': False,
             'description': 'It has three heads. Each head has its own will.',
             'pokeapi_id': 103, 'rarity': 'Rare'},
            {'name': 'Marowak', 'type': 'Ground', 'level_requirement': 12, 'is_starter': False,
             'description': 'It has mastered the bone club. Very aggressive.',
             'pokeapi_id': 105, 'rarity': 'Rare'},
            {'name': 'Weezing', 'type': 'Poison', 'level_requirement': 12, 'is_starter': False,
             'description': 'It mixes two different gases to create deadly poisons.',
             'pokeapi_id': 110, 'rarity': 'Rare'},
            {'name': 'Kangaskhan', 'type': 'Normal', 'level_requirement': 10, 'is_starter': False,
             'description': 'It carries its young in its pouch. Very protective.',
             'pokeapi_id': 115, 'rarity': 'Epic'},
            {'name': 'Horsea', 'type': 'Water', 'level_requirement': 8, 'is_starter': False,
             'description': 'It can create whirlpools. It lives in oceans.',
             'pokeapi_id': 116, 'rarity': 'Uncommon'},
            {'name': 'Seadra', 'type': 'Water', 'level_requirement': 12, 'is_starter': False,
             'description': 'Its fins secrete poison. Very dangerous to touch.',
             'pokeapi_id': 117, 'rarity': 'Rare'},
            {'name': 'Goldeen', 'type': 'Water', 'level_requirement': 7, 'is_starter': False,
             'description': 'Its dorsal fin is very sharp. It can slice through ice.',
             'pokeapi_id': 118, 'rarity': 'Common'},
            {'name': 'Seaking', 'type': 'Water', 'level_requirement': 12, 'is_starter': False,
             'description': 'It uses its horn to drill through ice. Very strong.',
             'pokeapi_id': 119, 'rarity': 'Rare'},
            {'name': 'Staryu', 'type': 'Water', 'level_requirement': 8, 'is_starter': False,
             'description': 'Its core is very bright. It can be seen from space.',
             'pokeapi_id': 120, 'rarity': 'Uncommon'},
            {'name': 'Starmie', 'type': 'Water', 'level_requirement': 12, 'is_starter': False,
             'description': 'Its central core glows with the colors of the rainbow.',
             'pokeapi_id': 121, 'rarity': 'Rare'},
            {'name': 'MrMime', 'type': 'Psychic', 'level_requirement': 10, 'is_starter': False,
             'description': 'It can create invisible walls using its mime powers.',
             'pokeapi_id': 122, 'rarity': 'Epic'},
            {'name': 'Scyther', 'type': 'Bug', 'level_requirement': 10, 'is_starter': False,
             'description': 'Its scythes are sharper than swords. Very fast.',
             'pokeapi_id': 123, 'rarity': 'Epic'},
            {'name': 'Jynx', 'type': 'Ice', 'level_requirement': 12, 'is_starter': False,
             'description': 'It can freeze opponents with its icy dance.',
             'pokeapi_id': 124, 'rarity': 'Epic'},
            {'name': 'Electabuzz', 'type': 'Electric', 'level_requirement': 10, 'is_starter': False,
             'description': 'It generates electricity from its body. Very dangerous.',
             'pokeapi_id': 125, 'rarity': 'Rare'},
            {'name': 'Magmar', 'type': 'Fire', 'level_requirement': 10, 'is_starter': False,
             'description': 'Its body is burning. It can create fire at will.',
             'pokeapi_id': 126, 'rarity': 'Rare'},
            {'name': 'Pinsir', 'type': 'Bug', 'level_requirement': 10, 'is_starter': False,
             'description': 'It grips prey with its horns. Very powerful.',
             'pokeapi_id': 127, 'rarity': 'Epic'},
            {'name': 'Tauros', 'type': 'Normal', 'level_requirement': 10, 'is_starter': False,
             'description': 'It runs in herds. Very aggressive when threatened.',
             'pokeapi_id': 128, 'rarity': 'Rare'},
            {'name': 'Magikarp', 'type': 'Water', 'level_requirement': 5, 'is_starter': False,
             'description': 'It is the weakest Pokemon. It can only splash.',
             'pokeapi_id': 129, 'rarity': 'Common'},
            {'name': 'Gyarados', 'type': 'Water', 'level_requirement': 14, 'is_starter': False,
             'description': 'Once it appears, it goes on a rampage. It remains enraged until it calms down.',
             'pokeapi_id': 130, 'rarity': 'Epic'},
            {'name': 'Lapras', 'type': 'Water', 'level_requirement': 12, 'is_starter': False,
             'description': 'It can carry people on its back across water. It loves to swim.',
             'pokeapi_id': 131, 'rarity': 'Rare'},
            {'name': 'Ditto', 'type': 'Normal', 'level_requirement': 8, 'is_starter': False,
             'description': 'It can transform into anything. It copies the opponents attacks perfectly.',
             'pokeapi_id': 132, 'rarity': 'Epic'},
            {'name': 'Eevee', 'type': 'Normal', 'level_requirement': 5, 'is_starter': False,
             'description': 'It has the ability to evolve into many different forms.',
             'pokeapi_id': 133, 'rarity': 'Uncommon'},
            {'name': 'Vaporeon', 'type': 'Water', 'level_requirement': 10, 'is_starter': False,
             'description': 'Its cell composition is similar to water. It can melt into water.',
             'pokeapi_id': 134, 'rarity': 'Epic'},
            {'name': 'Jolteon', 'type': 'Electric', 'level_requirement': 10, 'is_starter': False,
             'description': 'It concentrates the weak electric charges in its fur to produce bolts.',
             'pokeapi_id': 135, 'rarity': 'Epic'},
            {'name': 'Flareon', 'type': 'Fire', 'level_requirement': 10, 'is_starter': False,
             'description': 'It has a flame chamber in its body. Its fire burns at 3,000 degrees.',
             'pokeapi_id': 136, 'rarity': 'Epic'},
            {'name': 'Porygon', 'type': 'Normal', 'level_requirement': 8, 'is_starter': False,
             'description': 'It was created by technology. It can exist in digital space.',
             'pokeapi_id': 137, 'rarity': 'Rare'},
            {'name': 'Omanyte', 'type': 'Water', 'level_requirement': 10, 'is_starter': False,
             'description': 'A prehistoric Pokemon that lived in ancient seas.',
             'pokeapi_id': 138, 'rarity': 'Rare'},
            {'name': 'Omastar', 'type': 'Water', 'level_requirement': 14, 'is_starter': False,
             'description': 'It can crush enemies with its hard shell. Very powerful.',
             'pokeapi_id': 139, 'rarity': 'Epic'},
            {'name': 'Kabuto', 'type': 'Water', 'level_requirement': 10, 'is_starter': False,
             'description': 'A prehistoric Pokemon that has been revived from fossils.',
             'pokeapi_id': 140, 'rarity': 'Rare'},
            {'name': 'Kabutops', 'type': 'Water', 'level_requirement': 14, 'is_starter': False,
             'description': 'It can slice through prey with its sharp claws.',
             'pokeapi_id': 141, 'rarity': 'Epic'},
            {'name': 'Aerodactyl', 'type': 'Rock', 'level_requirement': 14, 'is_starter': False,
             'description': 'A prehistoric Pokemon that can fly. Very rare.',
             'pokeapi_id': 142, 'rarity': 'Epic'},
            {'name': 'Snorlax', 'type': 'Normal', 'level_requirement': 10, 'is_starter': False,
             'description': 'It is not satisfied unless it eats 900 pounds of food every day.',
             'pokeapi_id': 143, 'rarity': 'Epic'},
            {'name': 'Articuno', 'type': 'Ice', 'level_requirement': 15, 'is_starter': False,
             'description': 'A legendary bird Pokemon that can create blizzards.',
             'pokeapi_id': 144, 'rarity': 'Legendary'},
            {'name': 'Zapdos', 'type': 'Electric', 'level_requirement': 15, 'is_starter': False,
             'description': 'A legendary bird Pokemon that can create thunderstorms.',
             'pokeapi_id': 145, 'rarity': 'Legendary'},
            {'name': 'Moltres', 'type': 'Fire', 'level_requirement': 15, 'is_starter': False,
             'description': 'A legendary bird Pokemon that can create massive fires.',
             'pokeapi_id': 146, 'rarity': 'Legendary'},
            {'name': 'Dratini', 'type': 'Dragon', 'level_requirement': 10, 'is_starter': False,
             'description': 'It is the offspring of Dragonair. It sheds its skin as it grows.',
             'pokeapi_id': 147, 'rarity': 'Rare'},
            {'name': 'Dragonair', 'type': 'Dragon', 'level_requirement': 12, 'is_starter': False,
             'description': 'It stores energy by surrounding its body with a mystical aura.',
             'pokeapi_id': 148, 'rarity': 'Epic'},
            {'name': 'Dragonite', 'type': 'Dragon', 'level_requirement': 16, 'is_starter': False,
             'description': 'It can fly at speeds of 1,500 mph. Very powerful.',
             'pokeapi_id': 149, 'rarity': 'Legendary'},
            {'name': 'Mewtwo', 'type': 'Psychic', 'level_requirement': 20, 'is_starter': False,
             'description': 'A legendary Pokemon created by science. Extremely powerful.',
             'pokeapi_id': 150, 'rarity': 'Legendary'},
            {'name': 'Mew', 'type': 'Psychic', 'level_requirement': 18, 'is_starter': False,
             'description': 'A mythical Pokemon from ancient times. It can learn any move.',
             'pokeapi_id': 151, 'rarity': 'Legendary'},
            
            # Gen 2
            {'name': 'Chikorita', 'type': 'Grass', 'level_requirement': 1, 'is_starter': True,
             'description': 'It waves its leaf around to keep cool on hot days.',
             'pokeapi_id': 152, 'rarity': 'Common'},
            {'name': 'Cyndaquil', 'type': 'Fire', 'level_requirement': 1, 'is_starter': True,
             'description': 'It is timid and curls up into a ball when it is surprised.',
             'pokeapi_id': 155, 'rarity': 'Common'},
            {'name': 'Totodile', 'type': 'Water', 'level_requirement': 1, 'is_starter': True,
             'description': 'It has a big mouth and is very greedy. It bites anything.',
             'pokeapi_id': 158, 'rarity': 'Common'},
            {'name': 'Sentret', 'type': 'Normal', 'level_requirement': 4, 'is_starter': False,
             'description': 'It stands guard by taking turns with its companions. Very loyal.',
             'pokeapi_id': 161, 'rarity': 'Common'},
            {'name': 'Hoothoot', 'type': 'Normal', 'level_requirement': 4, 'is_starter': False,
             'description': 'It begins to hoot at the same time every day without fail.',
             'pokeapi_id': 163, 'rarity': 'Common'},
            {'name': 'Ledyba', 'type': 'Bug', 'level_requirement': 4, 'is_starter': False,
             'description': 'It is very timid. If it senses danger, it hides in grass.',
             'pokeapi_id': 165, 'rarity': 'Common'},
            {'name': 'Spinarak', 'type': 'Bug', 'level_requirement': 4, 'is_starter': False,
             'description': 'It sets a trap of webbing around its nest. Very patient.',
             'pokeapi_id': 167, 'rarity': 'Common'},
            {'name': 'Cleffa', 'type': 'Fairy', 'level_requirement': 4, 'is_starter': False,
             'description': 'It is said to arrive on shooting stars. Very adorable.',
             'pokeapi_id': 173, 'rarity': 'Uncommon'},
            {'name': 'Igglybuff', 'type': 'Normal', 'level_requirement': 4, 'is_starter': False,
             'description': 'Its body is soft and bouncy. It walks with small hops.',
             'pokeapi_id': 174, 'rarity': 'Common'},
            {'name': 'Togepi', 'type': 'Fairy', 'level_requirement': 5, 'is_starter': False,
             'description': 'It is said to bring good luck. Its shell is very precious.',
             'pokeapi_id': 175, 'rarity': 'Rare'},
            {'name': 'Natu', 'type': 'Psychic', 'level_requirement': 5, 'is_starter': False,
             'description': 'It can see into the future. It flaps its tiny wings to fly.',
             'pokeapi_id': 177, 'rarity': 'Uncommon'},
            {'name': 'Mareep', 'type': 'Electric', 'level_requirement': 5, 'is_starter': False,
             'description': 'Its wool is useful for storing electricity. It glows when charged.',
             'pokeapi_id': 179, 'rarity': 'Common'},
            {'name': 'Flaaffy', 'type': 'Electric', 'level_requirement': 7, 'is_starter': False,
             'description': 'It generates electricity by storing it in its fluffy wool.',
             'pokeapi_id': 180, 'rarity': 'Uncommon'},
            {'name': 'Ampharos', 'type': 'Electric', 'level_requirement': 12, 'is_starter': False,
             'description': 'It emits a powerful light from its tail. It was a ancient beacon.',
             'pokeapi_id': 181, 'rarity': 'Epic'},
            {'name': 'Bellossom', 'type': 'Grass', 'level_requirement': 12, 'is_starter': False,
             'description': 'It dances in sunny weather. Its flowers release a sweet scent.',
             'pokeapi_id': 182, 'rarity': 'Rare'},
            {'name': 'Marill', 'type': 'Water', 'level_requirement': 6, 'is_starter': False,
             'description': 'The water inside its floaty tail is useful for fighting fires.',
             'pokeapi_id': 184, 'rarity': 'Uncommon'},
            {'name': 'Azumarill', 'type': 'Water', 'level_requirement': 10, 'is_starter': False,
             'description': 'It can hide in water using its bubble-like body.',
             'pokeapi_id': 185, 'rarity': 'Rare'},
            {'name': 'Sunkern', 'type': 'Grass', 'level_requirement': 5, 'is_starter': False,
             'description': 'It eats only a leaf a day. Very small and weak.',
             'pokeapi_id': 191, 'rarity': 'Common'},
            {'name': 'Sunflora', 'type': 'Grass', 'level_requirement': 10, 'is_starter': False,
             'description': 'It converts sunlight into energy. It is most active in summer.',
             'pokeapi_id': 192, 'rarity': 'Rare'},
            {'name': 'Wooper', 'type': 'Water', 'level_requirement': 6, 'is_starter': False,
             'description': 'It lives in cold water. It leaves the water to search for food.',
             'pokeapi_id': 194, 'rarity': 'Common'},
            {'name': 'Quagsire', 'type': 'Water', 'level_requirement': 10, 'is_starter': False,
             'description': 'It is very careless. It bumps into things while wandering.',
             'pokeapi_id': 195, 'rarity': 'Rare'},
            {'name': 'Murkrow', 'type': 'Dark', 'level_requirement': 7, 'is_starter': False,
             'description': 'It is said to bring bad luck. It loves shiny objects.',
             'pokeapi_id': 198, 'rarity': 'Rare'},
            {'name': 'Misdreavus', 'type': 'Ghost', 'level_requirement': 8, 'is_starter': False,
             'description': 'It loves to frighten people. It can create strange sounds.',
             'pokeapi_id': 200, 'rarity': 'Rare'},
            {'name': 'Wynaut', 'type': 'Psychic', 'level_requirement': 6, 'is_starter': False,
             'description': 'It gathers in colonies. It squirts water from its tail.',
             'pokeapi_id': 202, 'rarity': 'Uncommon'},
            {'name': 'Girafarig', 'type': 'Normal', 'level_requirement': 7, 'is_starter': False,
             'description': 'It has a second head on its tail. It can see in all directions.',
             'pokeapi_id': 203, 'rarity': 'Rare'},
            {'name': 'Pineco', 'type': 'Bug', 'level_requirement': 6, 'is_starter': False,
             'description': 'It hangs from trees. It drops on enemies from above.',
             'pokeapi_id': 204, 'rarity': 'Common'},
            {'name': 'Forretress', 'type': 'Bug', 'level_requirement': 10, 'is_starter': False,
             'description': 'It hides in its shell. It waits for prey to come.',
             'pokeapi_id': 205, 'rarity': 'Rare'},
            {'name': 'Dunsparce', 'type': 'Normal', 'level_requirement': 7, 'is_starter': False,
             'description': 'It hides in burrows. Its drill-like tail can break rock.',
             'pokeapi_id': 206, 'rarity': 'Uncommon'},
            {'name': 'Gligar', 'type': 'Ground', 'level_requirement': 8, 'is_starter': False,
             'description': 'It glides silently. It grips prey with its sharp claws.',
             'pokeapi_id': 207, 'rarity': 'Rare'},
            {'name': 'Steelix', 'type': 'Steel', 'level_requirement': 12, 'is_starter': False,
             'description': 'Its body is harder than steel. It can burrow through rock.',
             'pokeapi_id': 208, 'rarity': 'Epic'},
            {'name': 'Scizor', 'type': 'Bug', 'level_requirement': 12, 'is_starter': False,
             'description': 'It has powerful pincers. Very aggressive.',
             'pokeapi_id': 212, 'rarity': 'Epic'},
            {'name': 'Sneasel', 'type': 'Dark', 'level_requirement': 10, 'is_starter': False,
             'description': 'It is very agile. It can climb icy walls.',
             'pokeapi_id': 215, 'rarity': 'Rare'},
            {'name': 'Teddiursa', 'type': 'Normal', 'level_requirement': 7, 'is_starter': False,
             'description': 'It loves honey. It has a sweet tooth.',
             'pokeapi_id': 216, 'rarity': 'Uncommon'},
            {'name': 'Ursaring', 'type': 'Normal', 'level_requirement': 12, 'is_starter': False,
             'description': 'It is very strong. It can break trees with its paws.',
             'pokeapi_id': 217, 'rarity': 'Epic'},
            {'name': 'Slugma', 'type': 'Fire', 'level_requirement': 7, 'is_starter': False,
             'description': 'Its body is hot. It leaves a trail of magma.',
             'pokeapi_id': 218, 'rarity': 'Common'},
            {'name': 'Magcargo', 'type': 'Fire', 'level_requirement': 12, 'is_starter': False,
             'description': 'Its body is magma. The fire on its back never goes out.',
             'pokeapi_id': 219, 'rarity': 'Rare'},
            {'name': 'Swinub', 'type': 'Ice', 'level_requirement': 7, 'is_starter': False,
             'description': 'It lives in cold regions. It digs for food.',
             'pokeapi_id': 220, 'rarity': 'Uncommon'},
            {'name': 'Piloswine', 'type': 'Ice', 'level_requirement': 10, 'is_starter': False,
             'description': 'It can work in extreme cold. Very strong.',
             'pokeapi_id': 221, 'rarity': 'Rare'},
            {'name': 'Corsola', 'type': 'Water', 'level_requirement': 8, 'is_starter': False,
             'description': 'It lives in warm seas. Its branches glow.',
             'pokeapi_id': 222, 'rarity': 'Uncommon'},
            {'name': 'Remoraid', 'type': 'Water', 'level_requirement': 7, 'is_starter': False,
             'description': 'It squirts water at prey. Very accurate.',
             'pokeapi_id': 223, 'rarity': 'Common'},
            {'name': 'Octillery', 'type': 'Water', 'level_requirement': 12, 'is_starter': False,
             'description': 'It can shoot ink to confuse enemies. Very smart.',
             'pokeapi_id': 224, 'rarity': 'Rare'},
            {'name': 'Delibird', 'type': 'Ice', 'level_requirement': 10, 'is_starter': False,
             'description': 'It carries food in its tail. Very generous.',
             'pokeapi_id': 225, 'rarity': 'Rare'},
            {'name': 'Mantine', 'type': 'Water', 'level_requirement': 12, 'is_starter': False,
             'description': 'It can swim gracefully through the ocean.',
             'pokeapi_id': 226, 'rarity': 'Rare'},
            {'name': 'Skarmory', 'type': 'Steel', 'level_requirement': 12, 'is_starter': False,
             'description': 'Its body is hard as steel. It can fly at high speeds.',
             'pokeapi_id': 227, 'rarity': 'Epic'},
            {'name': 'Houndour', 'type': 'Dark', 'level_requirement': 7, 'is_starter': False,
             'description': 'It hunts in packs. It uses fire to corner prey.',
             'pokeapi_id': 228, 'rarity': 'Uncommon'},
            {'name': 'Houndoom', 'type': 'Dark', 'level_requirement': 12, 'is_starter': False,
             'description': 'It is very aggressive. Its fire is extremely hot.',
             'pokeapi_id': 229, 'rarity': 'Epic'},
            {'name': 'Kingdra', 'type': 'Dragon', 'level_requirement': 14, 'is_starter': False,
             'description': 'It sleeps in the deep ocean. Very powerful.',
             'pokeapi_id': 230, 'rarity': 'Epic'},
            {'name': 'Phanpy', 'type': 'Ground', 'level_requirement': 7, 'is_starter': False,
             'description': 'It is very playful. It sprays water from its trunk.',
             'pokeapi_id': 231, 'rarity': 'Common'},
            {'name': 'Donphan', 'type': 'Ground', 'level_requirement': 12, 'is_starter': False,
             'description': 'It can roll like a ball. Very strong.',
             'pokeapi_id': 232, 'rarity': 'Epic'},
            {'name': 'Porygon2', 'type': 'Normal', 'level_requirement': 12, 'is_starter': False,
             'description': 'An upgraded version of Porygon. Very advanced.',
             'pokeapi_id': 233, 'rarity': 'Epic'},
            {'name': 'Stantler', 'type': 'Normal', 'level_requirement': 10, 'is_starter': False,
             'description': 'Its antlers can create illusions. Very mysterious.',
             'pokeapi_id': 234, 'rarity': 'Rare'},
            {'name': 'Smeargle', 'type': 'Normal', 'level_requirement': 8, 'is_starter': False,
             'description': 'It can paint any picture. It leaves paint everywhere.',
             'pokeapi_id': 235, 'rarity': 'Uncommon'},
            {'name': 'Tyrogue', 'type': 'Fighting', 'level_requirement': 5, 'is_starter': False,
             'description': 'It is always full of energy. Very aggressive.',
             'pokeapi_id': 236, 'rarity': 'Uncommon'},
            {'name': 'Hitmontop', 'type': 'Fighting', 'level_requirement': 12, 'is_starter': False,
             'description': 'It can spin on its head. Very agile.',
             'pokeapi_id': 237, 'rarity': 'Epic'},
            {'name': 'Smoochum', 'type': 'Ice', 'level_requirement': 6, 'is_starter': False,
             'description': 'It is very curious. It loves to explore.',
             'pokeapi_id': 238, 'rarity': 'Uncommon'},
            {'name': 'Elekid', 'type': 'Electric', 'level_requirement': 6, 'is_starter': False,
             'description': 'It is always twitching with electricity.',
             'pokeapi_id': 239, 'rarity': 'Uncommon'},
            {'name': 'Magby', 'type': 'Fire', 'level_requirement': 6, 'is_starter': False,
             'description': 'It is always sweating. It can breathe fire.',
             'pokeapi_id': 240, 'rarity': 'Uncommon'},
            {'name': 'Miltank', 'type': 'Normal', 'level_requirement': 10, 'is_starter': False,
             'description': 'It produces delicious milk. Very useful.',
             'pokeapi_id': 241, 'rarity': 'Rare'},
            {'name': 'Blissey', 'type': 'Normal', 'level_requirement': 14, 'is_starter': False,
             'description': 'It brings happiness to people. Very kind.',
             'pokeapi_id': 242, 'rarity': 'Epic'},
            {'name': 'Raikou', 'type': 'Electric', 'level_requirement': 15, 'is_starter': False,
             'description': 'A legendary Pokemon that rides on the wind.',
             'pokeapi_id': 243, 'rarity': 'Legendary'},
            {'name': 'Entei', 'type': 'Fire', 'level_requirement': 15, 'is_starter': False,
             'description': 'A legendary Pokemon created by fire.',
             'pokeapi_id': 244, 'rarity': 'Legendary'},
            {'name': 'Suicune', 'type': 'Water', 'level_requirement': 15, 'is_starter': False,
             'description': 'A legendary Pokemon that can run across water.',
             'pokeapi_id': 245, 'rarity': 'Legendary'},
            {'name': 'Larvitar', 'type': 'Rock', 'level_requirement': 10, 'is_starter': False,
             'description': 'It eats mountains. Very hungry.',
             'pokeapi_id': 246, 'rarity': 'Rare'},
            {'name': 'Pupitar', 'type': 'Rock', 'level_requirement': 12, 'is_starter': False,
             'description': 'It is very hard. It can withstand any attack.',
             'pokeapi_id': 247, 'rarity': 'Epic'},
            {'name': 'Tyranitar', 'type': 'Rock', 'level_requirement': 16, 'is_starter': False,
             'description': 'It can destroy mountains. Extremely powerful.',
             'pokeapi_id': 248, 'rarity': 'Legendary'},
            {'name': 'Lugia', 'type': 'Psychic', 'level_requirement': 18, 'is_starter': False,
             'description': 'A legendary Pokemon that controls the sky.',
             'pokeapi_id': 249, 'rarity': 'Legendary'},
            {'name': 'Ho-Oh', 'type': 'Fire', 'level_requirement': 18, 'is_starter': False,
             'description': 'A legendary Pokemon that grants wishes.',
             'pokeapi_id': 250, 'rarity': 'Legendary'},
            {'name': 'Celebi', 'type': 'Psychic', 'level_requirement': 16, 'is_starter': False,
             'description': 'A mythical Pokemon that can travel through time.',
             'pokeapi_id': 251, 'rarity': 'Legendary'},
        ]
        
        for data in pokemon_data:
            Pokemon.objects.create(**data)
        
        self.stdout.write(self.style.SUCCESS(f'Created {len(pokemon_data)} Pokemon'))
        
        # Create daily tasks
        tasks = [
            {'name': 'Daily Login', 'description': 'Log in to your account today', 
             'xp_reward': 10, 'egg_reward': 1, 'task_type': 'login', 'is_active': True},
            {'name': 'Explore Pokédex', 'description': 'View the Pokédex to see all Pokemon', 
             'xp_reward': 15, 'egg_reward': 1, 'task_type': 'view_pokedex', 'is_active': True},
            {'name': 'Build Your Team', 'description': 'Add a Pokemon to your team', 
             'xp_reward': 20, 'egg_reward': 2, 'task_type': 'add_team', 'is_active': True},
            {'name': 'Check Your Progress', 'description': 'View your trainer profile', 
             'xp_reward': 10, 'egg_reward': 1, 'task_type': 'view_profile', 'is_active': True},
            {'name': 'Catch 3 Pokemon', 'description': 'Add 3 Pokemon to your team', 
             'xp_reward': 30, 'egg_reward': 3, 'task_type': 'catch_pokemon', 'is_active': True},
        ]
        
        for task in tasks:
            DailyTask.objects.create(**task)
        
        self.stdout.write(self.style.SUCCESS(f'Created {len(tasks)} daily tasks'))
        self.stdout.write(self.style.SUCCESS('Database populated successfully with 150+ Pokemon!'))
